# Generated by Django 5.2.5 on 2025-10-02 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuario', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoESP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esp_id', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('REAL', 'ESP Real'), ('DEMO', 'Dados Fictícios')], default='DEMO', max_length=4)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='app_cad_usuario.usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo ESP',
                'verbose_name_plural': 'Dispositivos ESP',
                'unique_together': {('usuario', 'esp_id')},
            },
        ),
    ]
