# Generated by Django 5.2.5 on 2025-10-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuario', '0003_dispositivoesp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_recuperacao',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
