# Generated by Django 5.2.6 on 2025-09-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_ppm', models.FloatField(verbose_name='CO2 (ppm)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dispositivo_id', models.CharField(blank=True, default='ESP32_MQ135', max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='mq135_dados_timesta_14ec23_idx'), models.Index(fields=['dispositivo_id'], name='mq135_dados_disposi_a26f75_idx')],
            },
        ),
    ]
