# Generated by Django 5.2.5 on 2025-09-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_ppm', models.FloatField(verbose_name='CO2 (ppm)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dispositivo_id', models.CharField(blank=True, default='ESP32_MQ135', max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
