# Generated by Django 5.2.6 on 2025-09-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mq135', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DadosSensor',
            new_name='DadosSensor_mq135',
        ),
        migrations.AddIndex(
            model_name='dadossensor_mq135',
            index=models.Index(fields=['timestamp'], name='mq135_dados_timesta_14ec23_idx'),
        ),
        migrations.AddIndex(
            model_name='dadossensor_mq135',
            index=models.Index(fields=['dispositivo_id'], name='mq135_dados_disposi_a26f75_idx'),
        ),
        migrations.AlterModelTable(
            name='dadossensor_mq135',
            table='mq135_dadossensor',
        ),
    ]
