# Generated by Django 5.2.1 on 2025-10-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mq135', '0002_dadossensor_mq135_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadossensor_mq135',
            name='nh3_ppm',
        ),
        migrations.AddField(
            model_name='dadossensor_mq135',
            name='co2_ppm',
            field=models.FloatField(default=400.0, verbose_name='CO2 (ppm)'),
        ),
    ]
