# Generated by Django 5.2.5 on 2025-10-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mq135', '0003_remove_dadossensor_mq135_nh3_ppm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadossensor_mq135',
            name='co2_ppm',
            field=models.FloatField(verbose_name='CO2 (ppm)'),
        ),
    ]
