# Generated by Django 5.2.4 on 2025-09-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosSensor_mq7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_ppm', models.FloatField(verbose_name='CO (ppm)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dispositivo_id', models.CharField(blank=True, default='ESP32_MQ7', max_length=50)),
            ],
            options={
                'db_table': 'mq7_dadossensor',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='mq7_dadosse_timesta_8177d5_idx'), models.Index(fields=['dispositivo_id'], name='mq7_dadosse_disposi_2dfa97_idx')],
            },
        ),
    ]
