# Generated by Django 5.2.5 on 2025-09-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mq2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadossensor_mq2',
            old_name='co2_ppm',
            new_name='c4h10_ppm',
        ),
    ]
