# Generated by Django 5.2.5 on 2025-10-02 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuario', '0003_dispositivoesp'),
        ('mq2', '0002_rename_co2_ppm_dadossensor_mq2_c4h10_ppm'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadossensor_mq2',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cad_usuario.usuario'),
        ),
    ]
